pub fn suspicious_markers() -> &'static [&'static str] {
    &[
        "invoke-expression",
        "iex",
        "-encodedcommand",
        "frombase64string",
        "downloadstring",
        "downloadfile",
        "invoke-webrequest",
        "new-object net.webclient",
        "system.net.webclient",
        "fromcharcode",
        "atob(",
        "unescape(",
        "new function",
        "activexobject",
        "createobject",
        "wscript.shell",
        "adodb.stream",
        "msxml2.xmlhttp",
        "urlmon",
        "cmd /c",
        "cmd.exe /c",
        "powershell",
        "bitsadmin",
        "regsvr32",
        "rundll32",
        "mshta",
        "certutil",
    ]
}
